# Pipeline to build an image based on a Dockerfile and perform vulernability scan by Clair V2
name: $(BuildDefinitionName)_$(date:yyyyMMdd)_$(BuildID)$(rev:.r)

trigger:
- main

pool: app-agents

resources:
- repo: self

jobs:

- job: ClairScanContainerImage
  displayName: Scan container image by ClairV2

  steps:
  - task: Docker@2
    displayName: 'Build an image'
    inputs:
      command: build
      dockerFile: '**/Dockerfile'