# Pipeline to build an image based on a Dockerfile and perform vulernability scan by Clair V2
name: $(BuildDefinitionName)_$(date:yyyyMMdd)_$(BuildID)$(rev:.r)

trigger:
- main

pool: Azure Pipelines

resources:
- repo: self

jobs:

- job: ClairScanContainerImage
  displayName: Scan container image by ClairV2

  steps:
  - script: |
      RUN curl -fsSLO https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64
      mv clair-scanner_linux_amd64 clair-scanner
      chmod u+x clair-scanner
    displayName: "Install clair-scanner"

  - task: Docker@2
    displayName: 'Build an image'
    inputs:
      command: build
      dockerFile: '**/Dockerfile'